dialogflow_client:
  ros__parameters:
    results_topic: "/dialogflow_client/results"
    requests_topic: "/dialogflow_client/requests"
    project_id: "symmetric-axle-401017"
    play_audio: false
    use_audio_server: false
    server_name: "127.0.0.1"
    port: 4444
    debug: false
